config/routes.rb
Rails.application.routes.draw do
  get 'admin/index'

  devise_for :users
   root 'pages#index'
  #root :to => redirect("/users/sign_in")
  resources :pages
  resources :admins
  resources :abouts
  resources :awards
  resources :educations
  resources :interests
  resources :skills
end

app/models/about.rb
class About < ApplicationRecord
 belongs_to :user, optional: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/award.rb
class Award < ApplicationRecord
end

app/models/education.rb
class Education < ApplicationRecord
belongs_to :user
end

app/models/experience.rb
class Experience < ApplicationRecord
belongs_to :user
end

app/models/interest.rb
class Interest < ApplicationRecord
end

app/models/page.rb
class Page < ApplicationRecord
end

app/models/skill.rb
class Skill < ApplicationRecord
belongs_to :skill
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_one :about
  has_many :experiences
  has_many :educations
  has_many :skills
  accepts_nested_attributes_for :experiences, :educations, :skills

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/abouts_controller.rb
class AboutsController < ApplicationController
	def new
   @about = About.new
	end
	def create
		@about = About.new(permitted_params_about)
		if @about.save
				redirect_to admins_path
			else
				render new_about_path
		end
	end
  def show
 	
  end
  
  def edit
  	@about =About.last
  end

  def update
  	@about =About.last
    @about.update_attributes(first_name: params[:about][:first_name], last_name: params[:about][:last_name], description: params[:about][:description], email: params[:about][:email],  address: params[:about][:address])
  	if @about.save
  		redirect_to admins_path
  	else
  		render new_about_path
  	end	
  end

end

private
	def permitted_params_about
		params.require(:about).permit(:first_name, :last_name, :description, :email, :address)
		
	end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
	def index
	 	@user = User.last
	 	@about =About.last
	end
	def new
		
	end
end
  

app/controllers/educations_controller.rb
class EducationsController < ApplicationController
def new
	@user = User.last
	@edu = @user.educations.build
end

def create
	@user = User.last
	@user.attributes = education_params
	if @user.save
		redirect_to admins_path
	else
		render new_education_path
	end		
  end

 def edit
   @user =User.last
  end

  def update
   @user =User.last
   @user.attributes = education_params
    if @user.save
      redirect_to admins_path
   else
   	render edit_education_path(@user)
    end
   end 
end

private

def education_params
	params.require(:user).permit(educations_attributes: [:id, :unaversity_name, :subject, :marks, :qualified_degree, :user_id, :_destroy])
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  	@about =About.last
    @user =User.last
    @education =@user.educations
  end
  def new
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/awards_helper.rb
module AwardsHelper
end

app/helpers/educations_helper.rb
module EducationsHelper
end

app/helpers/experiences_helper.rb
module ExperiencesHelper
end

app/helpers/interests_helper.rb
module InterestsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/views/educations/_education_fields.html.erb
<div class='nested-fields'>
  <%= f.label :University_name%><br />
	<%= f.text_field :unaversity_name%>
	<br>
	<%= f.label :subject%><br />
	<%= f.text_field :subject%>
	<br>
	<%= f.label :marks%><br />
	<%= f.text_field :marks%>
	<br>
	<%= f.label :qualified_degree%><br />
	<%= f.text_field :qualified_degree %>
	<br>
	<%=f.hidden_field :user_id, value: @user.id %>
  <%= link_to_remove_association "Remove detail", f %>
</div>

app/views/educations/edit.html.erb
<h1>Education details</h1>

<%= form_for(@user, url: education_path(@user), method: :patch) do |f|%>
	
	<%=f.fields_for :educations do |education|%>
	  <%= render 'education_fields', :f => education%>
  <%end%>
  <%= link_to_add_association 'Add education detail', f, :educations %><br/>
   <%= f.submit 'edit'%>
<%end%>
    

app/views/educations/new.html.erb
<h1>Education details</h1>

<%= form_for(@user, url: educations_path ,method: :post) do |f|%>
	
	<%=f.fields_for :educations do |education|%>
	  <%= render 'education_fields', :f => education%>
  <%end%>
  <%= link_to_add_association 'Add education detail', f, :educations %><br/>
   <%= f.submit 'create'%>
<%end%>
    